[workspace]
git_release_enable = false
git_tag_enable = false
changelog_update = false
dependencies_update = false
publish = false

[[package]]
name = "regorus"
git_tag_enable = true
git_release_enable = true
changelog_update = true
publish = true
